version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
    commit-message:
      prefix: "deps: "
      include: "scope"
    labels:
      - "dependencies"
    reviewers:
      - eser

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
    commit-message:
      prefix: "ci: "
      include: "scope"
    labels:
      - "dependencies"
    reviewers:
      - eser
