repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=1024"]
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: forbid-new-submodules
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: pretty-format-json
        args: ["--autofix", "--no-ensure-ascii", "--no-sort-keys"]
      - id: trailing-whitespace
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []
  - repo: local
    hooks:
    - id: kebab-case-files-only
      name: kebab-case files only
      entry: filenames must be kebab-case only
      language: fail
      files: '(?!\.test\.[jt]sx?$)[^a-z0-9.\/\[\]@-]'
      exclude: |
        (?x)^(
          .github/ISSUE_TEMPLATE/bug_report.md|
          .github/ISSUE_TEMPLATE/feature_request.md|
          .github/PULL_REQUEST_TEMPLATE.md|
          .git/COMMIT_EDITMSG|
          public/CNAME|
          CODEOWNERS|
          CODE_OF_CONDUCT.md|
          CONTRIBUTING.md|
          LICENSE|
          README.md|
          SECURITY.md
        )$
    - id: check-integrity
      name: check integrity
      description: Check formatting, linting, license headers, types and run tests.
      entry: node --run check
      types_or: [javascript, jsx, ts, tsx, json, markdown]
      pass_filenames: false
      language: system
